export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREMENT_ITEM = 'INCREMENT_ITEM';
export const DECREMENT_ITEM = 'DECREMENT_ITEM';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const GET_BASEKET_VALUE = 'GET_BASEKET_VALUE';
